module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  rootDir: 'test',
  testMatch: ['**/*.spec.ts'],
  testPathIgnorePatterns: ['/node_modules/', '/dist/'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  moduleNameMapper: {
    '^@trade/shared(|/.*)$': '<rootDir>/../src/trade/shared/$1',
    '^@trade/shared$': '<rootDir>/../src/trade/shared',
    '^@trade/repository(|/.*)$': '<rootDir>/../src/trade/repository/$1',
    '^@trade/repository$': '<rootDir>/../src/trade/repository',
    '^@trade/state(|/.*)$': '<rootDir>/../src/trade/state/$1',
    '^@trade/parsing(|/.*)$': '<rootDir>/../src/trade/parsing/$1',
    '^@trade/engine(|/.*)$': '<rootDir>/../src/trade/engine/$1',
    '^@trade/ingestion(|/.*)$': '<rootDir>/../src/trade/ingestion/$1',
    '^@telegram/notification/single-trade(|/.*)$': '<rootDir>/../src/telegram/notification/single-trade/$1',
    '^@telegram/notification/trade-list(|/.*)$': '<rootDir>/../src/telegram/notification/trade-list/$1',
    '^@telegram/notification/trade-list$': '<rootDir>/../src/telegram/notification/trade-list',
    '^@price/stream(|/.*)$': '<rootDir>/../src/price/stream/$1',
    '^@price/exchange(|/.*)$': '<rootDir>/../src/price/exchange/$1',
    '^@price/cache(|/.*)$': '<rootDir>/../src/price/cache/$1',
    '^@telegram/command(|/.*)$': '<rootDir>/../src/telegram/command/$1',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
  ],
  coverageDirectory: '../coverage-e2e',
  coverageReporters: ['text', 'lcov', 'html'],
  verbose: true,
  testTimeout: 30000,
  setupFilesAfterEnv: ['<rootDir>/setup.ts'],
};