module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  rootDir: 'test',
  testMatch: ['**/*.spec.ts'],
  testPathIgnorePatterns: ['/node_modules/', '/dist/'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  moduleNameMapper: {
    '^@shared(|/.*)$': '<rootDir>/../src/shared/$1',
    '^@trade/shared(|/.*)$': '<rootDir>/../src/trade/shared/$1',
    '^@trade/shared$': '<rootDir>/../src/trade/shared',
    '^@trade/repository(|/.*)$': '<rootDir>/../src/trade/repository/$1',
    '^@trade/repository$': '<rootDir>/../src/trade/repository',
    '^@trade/state(|/.*)$': '<rootDir>/../src/trade/state/$1',
    '^@trade/parsing(|/.*)$': '<rootDir>/../src/trade/parsing/$1',
    '^@trade/engine(|/.*)$': '<rootDir>/../src/trade/engine/$1',
    '^@trade/ingestion(|/.*)$': '<rootDir>/../src/trade/ingestion/$1',
    '^@trade/history(|/.*)$': '<rootDir>/../src/trade/history/$1',
    '^@trade/domain(|/.*)$': '<rootDir>/../src/trade/domain/$1',
    '^@trade/trigger(|/.*)$': '<rootDir>/../src/trade/trigger/$1',
    '^@trade/statistics(|/.*)$': '<rootDir>/../src/trade/statistics/$1',
    '^@trade/share-card(|/.*)$': '<rootDir>/../src/trade/share-card/$1',
    '^@telegram/core(|/.*)$': '<rootDir>/../src/telegram/core/$1',
    '^@telegram/shared(|/.*)$': '<rootDir>/../src/telegram/shared/$1',
    '^@telegram/cmd(|/.*)$': '<rootDir>/../src/telegram/cmd/$1',
    '^@telegram/notification/single-trade(|/.*)$': '<rootDir>/../src/telegram/notification/single-trade/$1',
    '^@telegram/notification/trade-list(|/.*)$': '<rootDir>/../src/telegram/notification/trade-list/$1',
    '^@telegram/notification/trade-list$': '<rootDir>/../src/telegram/notification/trade-list',
    '^@telegram/notification/trade-alerts(|/.*)$': '<rootDir>/../src/telegram/notification/trade-alerts/$1',
    '^@telegram/notification/trade-approval(|/.*)$': '<rootDir>/../src/telegram/notification/trade-approval/$1',
    '^@telegram/notification/shared(|/.*)$': '<rootDir>/../src/telegram/notification/shared/$1',
    '^@price/stream(|/.*)$': '<rootDir>/../src/price/stream/$1',
    '^@price/exchange(|/.*)$': '<rootDir>/../src/price/exchange/$1',
    '^@price/cache(|/.*)$': '<rootDir>/../src/price/cache/$1',
    '^@price/provider/binance(|/.*)$': '<rootDir>/../src/price/provider/binance/$1',
    '^@price/provider/shared(|/.*)$': '<rootDir>/../src/price/provider/shared/$1',
    '^@config(|/.*)$': '<rootDir>/../src/config/$1',
    '^@recovery(|/.*)$': '<rootDir>/../src/recovery/$1',
    '^@price/exchange/domain(|/.*)$': '<rootDir>/../src/price/exchange/domain/$1',
    '^@price/stream/domain(|/.*)$': '<rootDir>/../src/price/stream/domain/$1',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
  ],
  coverageDirectory: '../coverage-e2e',
  coverageReporters: ['text', 'lcov', 'html'],
  verbose: true,
  testTimeout: 30000,
  setupFilesAfterEnv: ['<rootDir>/setup.ts'],
};