module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  rootDir: 'src',
  testMatch: ['**/__tests__/**/*.spec.ts'],
  testPathIgnorePatterns: ['/node_modules/', '/dist/'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  moduleNameMapper: {
    '^@shared(|/.*)$': '<rootDir>/shared/$1',
    '^@trade/shared(|/.*)$': '<rootDir>/trade/shared/$1',
    '^@trade/repository(|/.*)$': '<rootDir>/trade/repository/$1',
    '^@trade/state(|/.*)$': '<rootDir>/trade/state/$1',
    '^@trade/parsing(|/.*)$': '<rootDir>/trade/parsing/$1',
    '^@trade/engine(|/.*)$': '<rootDir>/trade/engine/$1',
    '^@trade/ingestion(|/.*)$': '<rootDir>/trade/ingestion/$1',
    '^@trade/statistics(|/.*)$': '<rootDir>/trade/statistics/$1',
    '^@trade/history(|/.*)$': '<rootDir>/trade/history/$1',
    '^@trade/domain(|/.*)$': '<rootDir>/trade/domain/$1',
    '^@telegram/core(|/.*)$': '<rootDir>/telegram/core/$1',
    '^@telegram/command(|/.*)$': '<rootDir>/telegram/command/$1',
    '^@telegram/shared(|/.*)$': '<rootDir>/telegram/shared/$1',
    '^@telegram/notification/trade-confirmation(|/.*)$': '<rootDir>/telegram/notification/trade-confirmation/$1',
    '^@telegram/notification/single-trade(|/.*)$': '<rootDir>/telegram/notification/single-trade/$1',
    '^@telegram/notification/trade-list(|/.*)$': '<rootDir>/telegram/notification/trade-list/$1',
    '^@telegram/notification/trade-alerts(|/.*)$': '<rootDir>/telegram/notification/trade-alerts/$1',
    '^@telegram/notification/trade-approval(|/.*)$': '<rootDir>/telegram/notification/trade-approval/$1',
    '^@price/stream(|/.*)$': '<rootDir>/price/stream/$1',
    '^@price/exchange(|/.*)$': '<rootDir>/price/exchange/$1',
    '^@price/cache(|/.*)$': '<rootDir>/price/cache/$1',
    '^@config(|/.*)$': '<rootDir>/config/$1',
  },
  collectCoverageFrom: [
    'trade/shared/**/*.ts',
    'trade/repository/**/*.ts',
    '!trade/**/*module.ts',
  ],
  coverageDirectory: '../coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  verbose: true,
  testTimeout: 10000,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
};